# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=25)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
